title: My first blog attempt
author: ProcRed
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A silly first attempt at a blog just to get used to the procedures involved with making static content.

# social links
github_username:  ProcRed # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
